Update Heroku access
buildpacks/registry-namespaces pull request #16
Opened 2021-08-02 19:54 UTC by joshwlewis

This PR is a bit of housekeeping around Heroku buildpack ownership.

- Removes @danielleadams. She's moved on to new adventures and we'll miss her.
- Adds me, @joshwlewis. I've joined the Heroku Languages team and will be publishing buildpacks (primarily for JavaScript).
- Adds @heroku-languages-buildpack-bot. It's bot user that we plan to use to automate buildpack publication, and should prevent automation from being bound to a specific employee.

2021-08-02 19:59 UTC, edmorley approved these changes
I don't suppose you could add me too? I presume my user ID is that in `501702+edmorley@users.noreply.github.com`? Thank you :-)

2021-08-02 20:01 UTC, hone commented
@joshwlewis do you want to add Ed in before we merge this?

2021-08-02 21:34 UTC, hone approved these changes

2021-08-02 21:44 UTC, hone requested changes

2021-08-02 21:44 UTC, hone commented on v1/heroku.json
> +{"owners":[{"id":1589,"type":"github_user"},{"id": 177877, "type": "github_user"}, {"id": 59744, "type": "github_user"}, {"id": 917672, "type": "github_user"}, {"id": 88346006, "type": "github_user"}
```suggestion
{"owners":[{"id":1589,"type":"github_user"},{"id": 177877, "type": "github_user"},{"id": 59744, "type": "github_user"}, {"id": 917672, "type": "github_user"},{"id": 88346006, "type": "github_user"},{"id": 501702, "type": "github_user"}]}
```

@joshwlewis actually can you cut the spaces?

2021-08-02 22:53 UTC, hone approved these changes

2021-08-03 03:58 UTC, merged

2022-10-29 09:58 UTC, edmorley commented
For posterity (so I don't have to figure out how to do this every time when checking off-boarding :-)), the current user ID to username mappings are as follows:

- `1589`: `@jkutner`
- `59744`: `@schneems`
- `501702`: `@edmorley`
- `177877`: `@Malax`
- `917672`: `@joshwlewis`
- `88346006`: `@heroku-languages-buildpack-bot`

To find out a username from an ID, use eg:
https://api.github.com/user/88346006

To find out an ID from a username, use eg:
https://api.github.com/users/heroku-languages-buildpack-bot

(Note `user` vs `users` - the endpoints aren't interchangeable)

2022-11-06 02:45 UTC, jkutner commented
@edmorley would be a great feature to add support for user names